name: flow
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.3
  - pip=21.3.1
  - setuptools=58.5.3
  - wheel=0.37.1
  - numpy=1.18.4
  - pandas=0.24.2
  - matplotlib=3.1.0
  - scipy=1.1.0
  - lxml=4.4.1
  - six=1.11.0
  - python-dateutil=2.7.3
  - pip:
      - ray==0.8.7
      - pyarrow==0.16.0
      - protobuf==3.19.6
      - cloudpickle==1.2.2
      - tensorflow==1.15.2
      - gym==0.14.0
      - pyglet==1.3.2
      - imutils==0.5.1
      - plotly==2.4.0
      - pyprind==2.11.2
      - nose2==0.8.0
      - cached_property
      - joblib==0.10.3
      - dill
      - lz4
      - setproctitle
      - psutil
      - opencv-python
      - boto3==1.10.45
      - redis==3.5.3
      - tabulate
      - numpydoc
      - tensorboardX==2.1
      - torch==1.4.0
